[package]
name = "bpfids"
version = "0.1.0"
edition = "2024"
resolver = "2"
[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
libbpf-rs = "0.25.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[build-dependencies]
bindgen = "0.71.0"
